### ISSUE TITLE
Feature Req: Generate the lastmod tag with the current date

### ISSUE THREAD

**Issue by henriqueleite42** [cicirello/generate-sitemap#29] opened 2021-05-12 19:13 UTC
**Is your feature request related to a problem? Please describe.**
It would be nice if the lastmod tag comes with a default value of the current date if any previous version of the page was found, since google search console doesn't seem to like empty lastmod tags.

**Additional context**
Currently, the lastmod tags are generated this way:
![image](https://user-images.githubusercontent.com/50992814/118031437-e8cb9d80-b33c-11eb-8282-0c8dfa69a431.png)

**Comment by cicirello** [comment] 2021-05-12 21:19
This should be easy to fix.  I'm assuming this was caused by a case where the file was created during the same workflow run, but not yet committed?  I just verified that would lead to this behavior.  Or did something else lead to the behavior you saw?

**Comment by henriqueleite42** [comment] 2021-05-13 11:33
Yes, It's exactly this.
The sitemap is generated during a GitHub Action and committed in another branch (gh-pages, of the project below), to work with GitHub Pages.

As this issue is extremely critical and we can't wait much for the fix, we moved to another package temporally to generate this sitemap, but the previous workflow was in the file `.github/workflows/deploy.yml` of [this PR](https://github.com/techmmunity/techmmunity.github.io/commit/da5841e1ca1c038c821507b67992477a522d42d0).

But anyway, I really liked this package, and I think it's would be great that this bug was corrected :smile:

**Closed** 2021-05-13 13:29 UTC
Labels: bug

**Comment by cicirello** [comment] 2021-05-13 13:38
@henriqueleite42 It is now fixed in v1.7.2. Although I also recently started using a v1 tag synchronized to the latest specific release to make it easier to get bug fixes, etc without the need to update workflow. So either v1.7.2 or v1 will get to the fixed version.
